### ISSUE TITLE
How to animate it smoothly  without mouse moving?

### ISSUE THREAD

**Issue by soheilyou** [JoanClaret/html5-canvas-animation#1]
How to animate it smoothly  without mouse moving?

**Comment by JoanClaret** [comment]
try commenting this 3 lines from  "js/3d-lines-animation.js" 

```javascript
document.addEventListener( 'mousemove', onDocumentMouseMove, false );
document.addEventListener( 'touchstart', onDocumentTouchStart, false );
document.addEventListener( 'touchmove', onDocumentTouchMove, false ); 
```

**Comment by JoanClaret** [comment]
Maybe you shoud take a look at threejs documentation

http://threejs.org/docs/

**Comment by soheilyou** [comment]
I just need to amimate it smothly ceaseless would you please give me a code to add in js fils ...

**Comment by JoanClaret** [comment]
Sorry, this isn't an issue.

If you want to develop new features check examples in http://threejs.org/ library and/or take a look at the documentation http://threejs.org/docs/

Good luck!
Joan
