### ISSUE TITLE
Content scrolling disabled on touch devices... workaround?

### ISSUE THREAD

**Issue by nacayoda** [JoanClaret/html5-canvas-animation#7]
Hey Joan,

I love this effect and have used it as a background on a website I am working on. 
I'm just wondering how I can enable scrolling on touch devices, as when on phones and tablets, scrolling by touch only moves the background animation, and the content below the fold is unavailable. Even http://joanclaret.github.io/html5-canvas-animation/ cannot be scrolled to access all the information on touch devices.

Perhaps there is a flag in the code somewhere to change this behaviour, but I have not been able to locate it.

I'd love to know if there is a workaround.

Thanks,
Anthony

**Comment by nacayoda** [comment]
Sorry, duplicate request! 
Already documented in CLOSED!

**Comment by JoanClaret** [comment]
👍
