### ISSUE TITLE
Animated background color

### ISSUE THREAD

**Issue by ghost** [JoanClaret/html5-canvas-animation#8]
I can't get the animated background color working. The page just has the default css color. I am sure that I'm missing something, do I need to activate it anywhere?

*haven't edited any files yet.

**Comment by ghost** [comment]
Very stupid of me. I have a SSL-certificate so I had to change the only url that links to another website: http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js to https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.2/jquery.min.js.

Thanks for the awesome script!

**Comment by JoanClaret** [comment]
👍
